# Generated by Django 3.0.3 on 2020-03-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Например, Courchevel 1850', max_length=128, verbose_name='Название сайта')),
            ],
        ),
    ]
