# Generated by Django 3.0.3 on 2020-03-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='KYNSI на Петровке', max_length=128, verbose_name='Название салона')),
                ('short_title', models.CharField(blank=True, default='', help_text='Петровка', max_length=64, verbose_name='Короткое название салона')),
                ('address', models.CharField(blank=True, default='', help_text='Петровка 20/1', max_length=128, verbose_name='Адрес')),
                ('time', models.CharField(blank=True, default='', help_text='Без выходных, с 10:00 до 22:00', max_length=128, verbose_name='Часы работы')),
                ('phone', models.CharField(blank=True, default='', help_text='+7 (495) 477-65-06', max_length=64, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_images', verbose_name='Картинка салона')),
                ('mango', models.CharField(blank=True, default='', help_text='11408', max_length=32, verbose_name='Id салона для mango')),
                ('reservi_id', models.CharField(blank=True, default='', help_text='2', max_length=32, verbose_name='Id салона для онлайн записи')),
                ('reservi_salon', models.CharField(blank=True, default='', help_text='388236cd-fddf-11e6-b3ff-d05349e841da', max_length=128, verbose_name='Код салона для онлайн записи')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, default='', help_text='Kynsi', max_length=128, verbose_name='Seo title')),
                ('seo_description', models.CharField(blank=True, default='', help_text='Салоны KYNSI: Сити, Петровка, Патриаршие | Маникюр и педикюр Christina Fitzgerald, La Ric | Укладки и окрашивание', max_length=1024, verbose_name='Seo title')),
                ('vk', models.CharField(blank=True, default='', help_text='https://vk.com/kynsi', max_length=256, verbose_name='Вконтакте')),
                ('facebook', models.CharField(blank=True, default='', help_text='https://www.facebook.com/kynsi.salon', max_length=256, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, default='', help_text='https://www.instagram.com/kynsisalon/', max_length=256, verbose_name='Instagram')),
                ('q_email', models.CharField(blank=True, default='', help_text='hello@kynsi.ru', max_length=256, verbose_name="Почта: 'Вопросы и предложения'")),
                ('work_email', models.CharField(blank=True, default='', help_text='work@kynsi.ru', max_length=256, verbose_name="Почта: 'Работайте с нами'")),
                ('pr_email', models.CharField(blank=True, default='', help_text='pr@kynsi.ru', max_length=256, verbose_name="Почта: 'Связь для прессы'")),
            ],
            options={
                'verbose_name': 'Основные настрйки сайта',
                'verbose_name_plural': 'Основные настрйки сайта',
            },
        ),
    ]
