# Generated by Django 3.0.3 on 2020-03-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='title',
            new_name='seo_title',
        ),
        migrations.AddField(
            model_name='site',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Например, Courchevel 1850', max_length=1024, verbose_name='Название сайта'),
        ),
    ]
