# Generated by Django 3.0.3 on 2020-03-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Маникюры', max_length=128, verbose_name='Название категории')),
                ('order', models.IntegerField(default=100, verbose_name='Порядок отображения категорию')),
                ('is_show', models.BooleanField(default=True, verbose_name='Показывать категорию на сайте')),
            ],
            options={
                'verbose_name': 'Услуги - категории',
                'verbose_name_plural': 'Услуги - категории',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Маникюры', max_length=128, verbose_name='Название подкатегории')),
                ('order', models.IntegerField(default=100, verbose_name='Порядок отображения подкатегорию')),
                ('is_show', models.BooleanField(default=True, verbose_name='Показывать подкатегорию на сайте')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='kynsi.Categories', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Услуги - подкатегории',
                'verbose_name_plural': 'Услуги - подкатегории',
            },
        ),
    ]
