# Generated by Django 3.0.3 on 2020-03-18 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0002_categories_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Маникюры', max_length=128, verbose_name='Название услуги')),
                ('order', models.IntegerField(default=100, verbose_name='Порядок отображения подкатегорию')),
                ('is_show', models.BooleanField(default=True, verbose_name='Показывать услугу на сайте')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='kynsi.SubCategories', verbose_name='Родительская подкатегория')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
