# Generated by Django 3.0.3 on 2020-03-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0002_auto_20200316_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='facebook',
            field=models.CharField(blank=True, default='', help_text='https://www.facebook.com/kynsi.salon', max_length=256, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='site',
            name='instagram',
            field=models.CharField(blank=True, default='', help_text='https://www.instagram.com/kynsisalon/', max_length=256, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='site',
            name='q_email',
            field=models.CharField(blank=True, default='', help_text='pr@kynsi.ru', max_length=256, verbose_name="Почта: 'Связь для прессы'"),
        ),
        migrations.AddField(
            model_name='site',
            name='vk',
            field=models.CharField(blank=True, default='', help_text='https://vk.com/kynsi', max_length=256, verbose_name='Вконтакте'),
        ),
        migrations.AddField(
            model_name='site',
            name='work_email',
            field=models.CharField(blank=True, default='', help_text='work@kynsi.ru', max_length=256, verbose_name="Почта: 'Работайте с нами'"),
        ),
        migrations.AlterField(
            model_name='site',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Салоны KYNSI: Сити, Петровка, Патриаршие | Маникюр и педикюр Christina Fitzgerald, La Ric | Укладки и окрашивание', max_length=1024, verbose_name='Seo title'),
        ),
        migrations.AlterField(
            model_name='site',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Kynsi', max_length=128, verbose_name='Seo title'),
        ),
    ]
