# Generated by Django 3.0.3 on 2020-03-18 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0003_auto_20200318_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalnosSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Слайдер салонов',
                'verbose_name_plural': 'Слайдер салонов',
            },
        ),
        migrations.CreateModel(
            name='SalonSliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='site_images', verbose_name='Картинки')),
                ('ordering', models.IntegerField(default=0, verbose_name='Порядок')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kynsi.SalnosSlider', verbose_name='Слайдер салона')),
            ],
            options={
                'verbose_name': 'Картинка для сладйера салонов',
                'verbose_name_plural': 'Картинка для сладйера салонов',
                'ordering': ['ordering'],
            },
        ),
    ]
