# Generated by Django 3.0.3 on 2020-03-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0004_salnosslider_salonsliderimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonsliderimage',
            old_name='certificate',
            new_name='salonslider',
        ),
        migrations.AddField(
            model_name='salonsliderimage',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Kure BAZAAR', max_length=128, verbose_name='Название картинки слайдера'),
        ),
    ]
