# Generated by Django 3.0.3 on 2020-03-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0004_auto_20200316_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Настрйоки сайта', 'verbose_name_plural': 'Настрйоки сайта'},
        ),
    ]
