# Generated by Django 3.0.3 on 2020-03-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0005_auto_20200316_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Основные настрйки сайта', 'verbose_name_plural': 'Основные настрйки сайта'},
        ),
        migrations.AddField(
            model_name='site',
            name='pr_email',
            field=models.CharField(blank=True, default='', help_text='pr@kynsi.ru', max_length=256, verbose_name="Почта: 'Связь для прессы'"),
        ),
        migrations.AlterField(
            model_name='site',
            name='q_email',
            field=models.CharField(blank=True, default='', help_text='hello@kynsi.ru', max_length=256, verbose_name="Почта: 'Вопросы и предложения'"),
        ),
    ]
