# Generated by Django 3.0.3 on 2020-03-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0005_auto_20200318_0800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalnosSlider',
            new_name='SalonsSlider',
        ),
        migrations.AlterField(
            model_name='salonsliderimage',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Kynsi Петровка', max_length=128, verbose_name='Название картинки слайдера'),
        ),
    ]
