# Generated by Django 3.0.3 on 2020-03-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0006_auto_20200316_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='KYNSI на Петровке', max_length=128, verbose_name='Название салона')),
                ('address', models.CharField(blank=True, default='', help_text='Петровка 20/1', max_length=128, verbose_name='Адрес')),
                ('time', models.CharField(blank=True, default='', help_text='Без выходных, с 10:00 до 22:00', max_length=128, verbose_name='Часы работы')),
                ('phone', models.CharField(blank=True, default='', help_text='+7 (495) 477-65-06', max_length=64, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_images', verbose_name='Картинка салона')),
                ('mango', models.CharField(blank=True, default='', help_text='11408', max_length=32, verbose_name='Id салона для mango')),
                ('reservi_id', models.CharField(blank=True, default='', help_text='2', max_length=32, verbose_name='Id салона для онлайн записи')),
                ('reservi_salon', models.CharField(blank=True, default='', help_text='388236cd-fddf-11e6-b3ff-d05349e841da', max_length=128, verbose_name='Код салона для онлайн записи')),
            ],
        ),
    ]
