# Generated by Django 3.0.3 on 2020-03-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0007_salons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salons',
            options={'verbose_name': 'Салон', 'verbose_name_plural': 'Салоны'},
        ),
    ]
