# Generated by Django 3.0.3 on 2020-03-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0007_blockslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockslider',
            name='text',
            field=models.TextField(blank=True, help_text='Абзацы в <p></p>', null=True, verbose_name='Текст блока'),
        ),
    ]
