# Generated by Django 3.0.3 on 2020-03-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0008_auto_20200318_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockslider',
            name='text',
            field=models.TextField(blank=True, help_text='Абзацы в &lt;p&gt;&lt;/p&gt;', null=True, verbose_name='Текст блока'),
        ),
    ]
