# Generated by Django 3.0.3 on 2020-03-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0010_auto_20200318_0833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockSlider',
            new_name='BlogSlider',
        ),
    ]
