# Generated by Django 3.0.3 on 2020-03-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0011_auto_20200318_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ya_map',
            field=models.TextField(blank=True, default='', help_text='https://yandex.ru/map-widget/v1/?um=constructor%3Ac2cc93efc49dcd1f934e880248f1c3531200eb3a94cc165c483d659df6bb1630&amp;source=constructor', max_length=256, verbose_name='src из яндекс карт'),
        ),
    ]
