# Generated by Django 3.0.3 on 2020-03-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0012_site_ya_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Слайдер instagram',
                'verbose_name_plural': 'Слайдер instagram',
            },
        ),
        migrations.CreateModel(
            name='InstaSliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='site_images', verbose_name='Картинки')),
                ('title', models.CharField(blank=True, default='', help_text='Kynsi Петровка', max_length=128, verbose_name='Название картинки слайдера')),
                ('ordering', models.IntegerField(default=0, verbose_name='Порядок')),
                ('salonslider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kynsi.InstaSlider', verbose_name='Слайдер салона')),
            ],
            options={
                'verbose_name': 'Картинка для сладйера instagram',
                'verbose_name_plural': 'Картинка для сладйера instagram',
                'ordering': ['ordering'],
            },
        ),
    ]
