# Generated by Django 3.0.3 on 2020-03-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0013_instaslider_instasliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='instasliderimage',
            name='url',
            field=models.CharField(blank=True, default='', help_text='https://www.instagram.com/p/BpM7dqQHUmz/', max_length=128, verbose_name='Сслыка на пост в insagram'),
        ),
    ]
