# Generated by Django 3.0.3 on 2020-03-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0014_instasliderimage_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instasliderimage',
            old_name='salonslider',
            new_name='slider',
        ),
    ]
