# Generated by Django 3.0.3 on 2020-03-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kynsi', '0015_auto_20200318_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instasliderimage',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kynsi.InstaSlider', verbose_name='Слайдер insagram'),
        ),
    ]
